# Data  Exploration

In [1]:
import pandas as pd
import numpy as np
from IPython.display import display
from collections import Counter

In [2]:
ngs_reads = pd.read_json('exported_datasets/complete_set.json')

After exporting/importing to json, dataformat of columns including dataframes is lost, restore to dfs:

In [3]:
ngs_reads['Basic Statistics'][0]

{'Measure': {'0': 'Filename',
  '1': 'File type',
  '2': 'Encoding',
  '3': 'Total Sequences',
  '4': 'Sequences flagged as poor quality',
  '5': 'Sequence length',
  '6': '%GC'},
 'Value': {'0': '200709_20-07968_20-00891_S21_L000_R2_001.fastq.gz',
  '1': 'Conventional base calls',
  '2': 'Sanger / Illumina 1.9',
  '3': 511669,
  '4': 0,
  '5': '35-301',
  '6': 34}}

In [4]:
for category in ngs_reads:
    if type(ngs_reads[category][0]) is dict:
        ngs_reads[category] = ngs_reads[category].apply(pd.DataFrame)
        print(category, 'converted to DF')
    elif type(ngs_reads[category][0]) is list:
        ngs_reads[category] = ngs_reads[category].apply(np.array)
        print(category, 'converted to np.array')

Basic Statistics converted to DF
Per base sequence quality converted to DF
Per tile sequence quality converted to DF
Per sequence quality scores converted to DF
Per base sequence content converted to DF
Per sequence GC content converted to DF
Per base N content converted to DF
Sequence Length Distribution converted to DF
Sequence Duplication Levels converted to DF
Overrepresented sequences converted to DF
Adapter Content converted to DF
Module Statuses converted to np.array
G converted to np.array
C converted to np.array
A converted to np.array
T converted to np.array
N converted to np.array
phred_means converted to np.array


#### Show example data

In [5]:
ngs_reads.head()

Basic Statistics  \
200709_20-07968_20-00891_S21_L000_R2_001                               Measure  \
0     ...   
200204_20-00746_19-03927_S9_L000_R1_001                                Measure  \
0     ...   
181002-18-6991-775-18_S1_L001_R1_001                                   Measure  \
0     ...   
200327_20-04028_20-00328_S25_L000_R1_001                               Measure  \
0     ...   
180727-18-5425-18-01680_S8_L001_R2_001                                 Measure  \
0     ...   

                                                                  Per base sequence quality  \
200709_20-07968_20-00891_S21_L000_R2_001         Base       Mean  Median  Lower Quartile...   
200204_20-00746_19-03927_S9_L000_R1_001          Base       Mean  Median  Lower Quartile...   
181002-18-6991-775-18_S1_L001_R1_001             Base       Mean  Median  Lower Quartile...   
200327_20-04028_20-00328_S25_L000_R1_001         Base       Mean  Median  Lower Quartile...   
180727-18-5425-18-01680_S8_L001_R2_001           Base       Mean  Median  Lower Quartile...   

                                                                  Per tile sequence quality  \
200709_20-07968_20-00891_S21_L000_R2_001        Tile     Base      Mean
0     1101      ...   
200204_20-00746_19-03927_S9_L000_R1_001         Tile     Base      Mean
0     1101      ...   
181002-18-6991-775-18_S1_L001_R1_001            Tile     Base      Mean
0     1101      ...   
200327_20-04028_20-00328_S25_L000_R1_001        Tile     Base      Mean
0     1101      ...   
180727-18-5425-18-01680_S8_L001_R2_001          Tile     Base       Mean
0     1102     ...   

                                                                Per sequence quality scores  \
200709_20-07968_20-00891_S21_L000_R2_001      Quality     Count
0         2       3.0
1 ...   
200204_20-00746_19-03927_S9_L000_R1_001       Quality    Count
0        13      2.0
1   ...   
181002-18-6991-775-18_S1_L001_R1_001          Quality      Count
0         2     1668.0
...   
200327_20-04028_20-00328_S25_L000_R1_001      Quality      Count
0        12        2.0
...   
180727-18-5425-18-01680_S8_L001_R2_001        Quality  Count
0        15    3.0
1       ...   

                                                                  Per base sequence content  \
200709_20-07968_20-00891_S21_L000_R2_001         Base          G          A          T  ...   
200204_20-00746_19-03927_S9_L000_R1_001          Base          G          A          T  ...   
181002-18-6991-775-18_S1_L001_R1_001             Base          G          A          T  ...   
200327_20-04028_20-00328_S25_L000_R1_001         Base          G          A          T  ...   
180727-18-5425-18-01680_S8_L001_R2_001           Base          G          A          T  ...   

                                                                    Per sequence GC content  \
200709_20-07968_20-00891_S21_L000_R2_001       GC Content  Count
0             0   3.00
...   
200204_20-00746_19-03927_S9_L000_R1_001        GC Content  Count
0             0    0.0
...   
181002-18-6991-775-18_S1_L001_R1_001           GC Content   Count
0             0  1668....   
200327_20-04028_20-00328_S25_L000_R1_001       GC Content  Count
0             0    0.0
...   
180727-18-5425-18-01680_S8_L001_R2_001         GC Content  Count
0             0    0.0
...   

                                                                         Per base N content  \
200709_20-07968_20-00891_S21_L000_R2_001         Base   N-Count
0         1  0.479607
1 ...   
200204_20-00746_19-03927_S9_L000_R1_001          Base   N-Count
0         1  0.009071
1 ...   
181002-18-6991-775-18_S1_L001_R1_001             Base   N-Count
0         1  0.029292
1 ...   
200327_20-04028_20-00328_S25_L000_R1_001         Base  N-Count
0         1      0.0
1   ...   
180727-18-5425-18-01680_S8_L001_R2_001           Base  N-Count
0         1      0.0
1   ...   

                                                               Sequence Length

## Data Exploration

#### Dimensions

In [6]:
ngs_reads.shape

(184, 23)

#### Available attributes for a read

In [7]:
ngs_reads.columns

Index(['Basic Statistics', 'Per base sequence quality',
       'Per tile sequence quality', 'Per sequence quality scores',
       'Per base sequence content', 'Per sequence GC content',
       'Per base N content', 'Sequence Length Distribution',
       'Sequence Duplication Levels', 'Overrepresented sequences',
       'Adapter Content', 'Module Statuses', 'organism', 'technology',
       'read_number', 'evaluation', 'G', 'C', 'A', 'T', 'N', 'phred_means',
       'n_content'],
      dtype='object')

#### Show complete data for one read

In [8]:
for category in ngs_reads:
    print(category)
    display(ngs_reads[category][0])

Basic Statistics


Measure  \
0                           Filename   
1                          File type   
2                           Encoding   
3                    Total Sequences   
4  Sequences flagged as poor quality   
5                    Sequence length   
6                                %GC   

                                               Value  
0  200709_20-07968_20-00891_S21_L000_R2_001.fastq.gz  
1                            Conventional base calls  
2                              Sanger / Illumina 1.9  
3                                             511669  
4                                                  0  
5                                             35-301  
6                                                 34

Per base sequence quality


Base       Mean  Median  Lower Quartile  Upper Quartile  \
0         1  33.548112    34.0            34.0            34.0   
1         2  33.729687    34.0            34.0            34.0   
2         3  33.802032    34.0            34.0            34.0   
3         4  33.765622    34.0            34.0            34.0   
4         5  33.781050    34.0            34.0            34.0   
..      ...        ...     ...             ...             ...   
63  280-284  22.746697    24.0            16.0            29.8   
64  285-289  21.384282    21.6            14.8            28.0   
65  290-294  20.308005    19.4            13.8            26.0   
66  295-299  19.056884    17.6            12.4            25.8   
67  300-301  16.385002    15.0            10.0            21.0   

    10th Percentile  90th Percentile  
0              34.0             34.0  
1              34.0             34.0  
2              34.0             34.0  
3              34.0             34.0  
4              34.0             34.0  
..              ...              ...  
63              9.2             35.0  
64              9.0             33.8  
65              8.8             32.6  
66              8.0             31.2  
67              8.0             27.5  

[68 rows x 7 columns]

Per tile sequence quality


Tile     Base      Mean
0     1101        1  0.030195
1     1101        2 -0.063217
2     1101        3 -0.013447
3     1101        4  0.033154
4     1101        5  0.003146
...    ...      ...       ...
2579  2119  280-284 -0.172432
2580  2119  285-289 -1.815671
2581  2119  290-294  0.908856
2582  2119  295-299  0.152131
2583  2119  300-301  1.562598

[2584 rows x 3 columns]

Per sequence quality scores


Quality     Count
0         2       3.0
1         3       0.0
2         4       0.0
3         5       0.0
4         6       0.0
5         7       0.0
6         8       0.0
7         9       1.0
8        10       1.0
9        11       3.0
10       12       5.0
11       13       7.0
12       14      17.0
13       15      35.0
14       16      52.0
15       17      86.0
16       18     131.0
17       19     176.0
18       20     248.0
19       21     310.0
20       22     409.0
21       23     460.0
22       24     681.0
23       25     735.0
24       26     910.0
25       27    1304.0
26       28    1653.0
27       29    2207.0
28       30    3080.0
29       31    4623.0
30       32    6943.0
31       33   11941.0
32       34   22473.0
33       35   40380.0
34       36   53547.0
35       37  359248.0

Per base sequence content


Base          G          A          T          C
0         1  33.577173  29.546459  16.551162  20.325206
1         2  11.681713  23.555987  46.734477  18.027823
2         3  13.436203  32.377225  36.775491  17.411081
3         4   9.389513  21.466741  49.746298  19.397448
4         5   8.786479  41.028132  41.738024   8.447365
..      ...        ...        ...        ...        ...
63  280-284  15.961072  36.683355  29.860565  17.495008
64  285-289  15.634858  37.584143  29.112107  17.668893
65  290-294  15.219478  38.393896  28.165586  18.221040
66  295-299  14.804239  38.594767  27.126277  19.474718
67  300-301  15.101565  41.679023  34.840851   8.378561

[68 rows x 5 columns]

Per sequence GC content


GC Content  Count
0             0   3.00
1             1   1.50
2             2   0.00
3             3   0.00
4             4   0.00
..          ...    ...
96           96   1.00
97           97   1.00
98           98   0.50
99           99   0.25
100         100   2.00

[101 rows x 2 columns]

Per base N content


Base   N-Count
0         1  0.479607
1         2  0.027948
2         3  0.015831
3         4  0.008795
4         5  0.008208
..      ...       ...
63  280-284  0.075072
64  285-289  0.060851
65  290-294  0.000000
66  295-299  0.322535
67  300-301  0.395047

[68 rows x 2 columns]

Sequence Length Distribution


Length    Count
0     30-39   4192.0
1     40-49   9763.0
2     50-59  12611.0
3     60-69  14726.0
4     70-79  17135.0
5     80-89  19612.0
6     90-99  21429.0
7   100-109  23278.0
8   110-119  24146.0
9   120-129  24394.0
10  130-139  24376.0
11  140-149  23713.0
12  150-159  23376.0
13  160-169  21844.0
14  170-179  20707.0
15  180-189  19556.0
16  190-199  17978.0
17  200-209  16894.0
18  210-219  15423.0
19  220-229  14167.0
20  230-239  12684.0
21  240-249  11542.0
22  250-259   9890.0
23  260-269   8316.0
24  270-279   6848.0
25  280-289   5738.0
26  290-299  10490.0
27  300-302  76841.0

Sequence Duplication Levels


Duplication Level  Percentage of deduplicated  Percentage of total
0                  1                   84.711280            69.592761
1                  2                   11.282641            18.538030
2                  3                    2.682884             6.612199
3                  4                    0.809507             2.660135
4                  5                    0.274517             1.127619
5                  6                    0.107702             0.530884
6                  7                    0.057656             0.331565
7                  8                    0.025161             0.165361
8                  9                    0.019868             0.146896
9                >10                    0.028784             0.294551
10               >50                    0.000000             0.000000
11              >100                    0.000000             0.000000
12              >500                    0.000000             0.000000
13               >1k                    0.000000             0.000000
14               >5k                    0.000000             0.000000
15             >10k+                    0.000000             0.000000

Overrepresented sequences


Empty DataFrame
Columns: []
Index: []

Adapter Content


Position  Illumina Universal Adapter  Illumina Small RNA 3' Adapter  \
0         1                         0.0                            0.0   
1         2                         0.0                            0.0   
2         3                         0.0                            0.0   
3         4                         0.0                            0.0   
4         5                         0.0                            0.0   
..      ...                         ...                            ...   
61  270-274                         0.0                            0.0   
62  275-279                         0.0                            0.0   
63  280-284                         0.0                            0.0   
64  285-289                         0.0                            0.0   
65      290                         0.0                            0.0   

    Illumina Small RNA 5' Adapter  Nextera Transposase Sequence  \
0                             0.0                      0.000000   
1                             0.0                      0.000000   
2                             0.0                      0.000000   
3                             0.0                      0.000000   
4                             0.0                      0.000000   
..                            ...                           ...   
61                            0.0                      0.147009   
62                            0.0                      0.174019   
63                            0.0                      0.195869   
64                            0.0                      0.205563   
65                            0.0                      0.205797   

    SOLID Small RNA Adapter  
0                       0.0  
1                       0.0  
2                       0.0  
3                       0.0  
4                       0.0  
..                      ...  
61                      0.0  
62                      0.0  
63                      0.0  
64                      0.0  
65                      0.0  

[66 rows x 6 columns]

Module Statuses


array(['pass', 'fail', 'pass', 'pass', 'fail', 'pass', 'pass', 'warn',
       'pass', 'pass', 'pass'], dtype='<U4')

organism


'Sau'

technology


'MS'

read_number


2

evaluation


'ugly'

G


array([0.33416134, 0.11678448, 0.13434076, 0.09388687, 0.08785758,
       0.19743037, 0.18671837, 0.18483238, 0.2077554 , 0.13135445,
       0.26779813, 0.16086767, 0.22543871, 0.16433476, 0.19081477,
       0.17259205, 0.15981425, 0.16462596, 0.17239465, 0.17080574,
       0.17105199, 0.17527738, 0.17157381, 0.17347738, 0.17782785,
       0.17129238, 0.17533405, 0.17511712, 0.17316859, 0.17331712,
       0.17638356, 0.17011584, 0.17232625, 0.17587151, 0.17179466,
       0.1743628 , 0.17700658, 0.17238805, 0.1735412 , 0.17566707,
       0.17162404, 0.1750345 , 0.17663822, 0.17321908, 0.17478495,
       0.17615196, 0.17415252, 0.17391896, 0.17689333, 0.17307731,
       0.17376987, 0.17746963, 0.17296089, 0.17451354, 0.17755333,
       0.17317544, 0.17277347, 0.17649856, 0.17383708, 0.17339617,
       0.17670969, 0.1712481 , 0.17403521, 0.1783706 , 0.17329699,
       0.1741464 , 0.1771688 , 0.17270086, 0.17368074, 0.1763224 ,
       0.17312603, 0.17413617, 0.17652291, 0.17187517, 0.17343

C


array([0.20227725, 0.18022784, 0.17408325, 0.19395742, 0.08446672,
       0.09116245, 0.13319158, 0.13993617, 0.29719604, 0.18366757,
       0.13067628, 0.16607221, 0.18119136, 0.24235003, 0.1780956 ,
       0.16800901, 0.16568915, 0.15794586, 0.16123314, 0.16641227,
       0.16645136, 0.16944157, 0.17034841, 0.16514583, 0.16936926,
       0.1709699 , 0.1667582 , 0.16905851, 0.17168521, 0.16692041,
       0.16927936, 0.17172625, 0.16940639, 0.16894711, 0.17273276,
       0.16790412, 0.16851063, 0.17270038, 0.16876231, 0.17029343,
       0.17175432, 0.16776067, 0.17159221, 0.17095536, 0.17025941,
       0.17042255, 0.17373344, 0.16843874, 0.17032213, 0.17268351,
       0.17023119, 0.1720594 , 0.1738775 , 0.16961698, 0.17155267,
       0.17356684, 0.17205193, 0.17266595, 0.17312795, 0.16986702,
       0.17214459, 0.1737137 , 0.17097174, 0.17234899, 0.17434075,
       0.1705333 , 0.17256745, 0.1745128 , 0.16999028, 0.17231497,
       0.17491376, 0.17040017, 0.17315609, 0.17442174, 0.17070

A


array([0.29404752, 0.23549404, 0.323721  , 0.21464853, 0.41024764,
       0.4865411 , 0.37124391, 0.42036356, 0.19621669, 0.30456213,
       0.2955309 , 0.29210877, 0.26165353, 0.25305813, 0.35262836,
       0.3489932 , 0.33416721, 0.33805058, 0.33295939, 0.32629102,
       0.32659395, 0.31979268, 0.32379917, 0.32664086, 0.31988453,
       0.3240122 , 0.32815746, 0.32601154, 0.32589232, 0.32852684,
       0.32221807, 0.32507344, 0.32494836, 0.32091254, 0.32225912,
       0.32638868, 0.32413314, 0.32424904, 0.32696541, 0.32397527,
       0.32375612, 0.32656499, 0.32210919, 0.3229697 , 0.32474798,
       0.32265516, 0.32258567, 0.32772711, 0.32345848, 0.32364571,
       0.3247347 , 0.32137161, 0.32260577, 0.32557267, 0.32117272,
       0.32336411, 0.32501288, 0.32090777, 0.32303351, 0.32521341,
       0.32216661, 0.32322141, 0.32505179, 0.32157517, 0.32254158,
       0.32383198, 0.32167139, 0.32313885, 0.32535851, 0.32124445,
       0.32159291, 0.32485222, 0.32107713, 0.32363868, 0.32587

T


array([0.16471782, 0.46721416, 0.36769669, 0.49741923, 0.41734598,
       0.22483285, 0.3088266 , 0.25486203, 0.298826  , 0.38035527,
       0.30598883, 0.38094549, 0.33169686, 0.34023949, 0.27842414,
       0.31038425, 0.3402903 , 0.3393307 , 0.33335613, 0.33638739,
       0.33581671, 0.33534766, 0.33408317, 0.33454245, 0.33268969,
       0.3334988 , 0.32950013, 0.32955876, 0.32919329, 0.3310695 ,
       0.33172813, 0.33234181, 0.33220109, 0.33276786, 0.33118285,
       0.33125425, 0.33034376, 0.33058002, 0.33067205, 0.32997752,
       0.33286553, 0.33063984, 0.32966038, 0.3328499 , 0.33020368,
       0.33076635, 0.32952838, 0.3299152 , 0.32932606, 0.33056334,
       0.33125618, 0.32908523, 0.3305437 , 0.33021771, 0.32965011,
       0.32979576, 0.33003295, 0.32986828, 0.32993774, 0.33141621,
       0.32891089, 0.33175872, 0.32987056, 0.32770524, 0.32982068,
       0.33148832, 0.32859236, 0.32964749, 0.33097047, 0.33011606,
       0.33017956, 0.33052366, 0.32924172, 0.32987034, 0.32998

N


array([4.7960693e-03, 2.7947760e-04, 1.5830550e-04, 8.7947500e-05,
       8.2084300e-05, 3.3224600e-05, 1.9543900e-05, 5.8632000e-06,
       5.8632000e-06, 6.0586000e-05, 5.8632000e-06, 5.8632000e-06,
       1.9543900e-05, 1.7589500e-05, 3.7133400e-05, 2.1498300e-05,
       3.9087800e-05, 4.6905300e-05, 5.6677300e-05, 1.0358260e-04,
       8.5993100e-05, 1.4071600e-04, 1.9543880e-04, 1.9348450e-04,
       2.2866350e-04, 2.2670910e-04, 2.5016170e-04, 2.5407050e-04,
       6.0586000e-05, 1.6612300e-04, 3.9087770e-04, 7.4266760e-04,
       1.1179102e-03, 1.5009704e-03, 2.0306096e-03, 9.0139300e-05,
       5.8850000e-06, 8.2501100e-05, 5.9022900e-05, 8.6703400e-05,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 5.9519000e-06,
       3.9750000e-06, 3.9829000e-06, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 3.0137800e-05, 8.0562000e-06, 1.4131200e-05,
       1.2140600e-05, 7.9107700e-05, 7.1170200e-05, 9.7850700e-05,
       1.2877220e-04, 5.9436100e-05, 6.3718700e-05, 1.0719370e

phred_means


array([33.54811216, 33.72968657, 33.80203217, 33.76562192, 33.78104986,
       37.60021225, 37.60590929, 37.60169954, 37.62667662, 37.60178748,
       37.63164272, 37.64041988, 37.6441039 , 37.60425001, 37.58689895,
       37.56939936, 37.57773482, 37.58482144, 37.58288268, 37.59896339,
       37.5726456 , 37.55945738, 37.5537877 , 37.52656893, 37.50855924,
       37.55382288, 37.51920284, 37.51124457, 37.55429193, 37.53084709,
       37.51973639, 37.47820564, 37.51061917, 37.4711327 , 37.44154131,
       37.47623946, 37.48134656, 37.47913507, 37.49838376, 37.48086317,
       37.49624076, 37.50387713, 37.45501859, 37.48342982, 37.45610601,
       37.46191347, 37.48050792, 37.48512941, 37.46629501, 37.46697702,
       37.47507316, 37.46768196, 37.44298375, 37.46270074, 37.45973293,
       37.46373305, 37.42031249, 37.44941066, 37.39990093, 37.42126311,
       37.38341924, 37.40023972, 37.42169965, 37.42038003, 37.41931388,
       37.40620522, 37.37638451, 37.3779914 , 37.41592112, 37.38

n_content


0.0001910136

#### target distribution

In [9]:
num_reads = ngs_reads.shape[0]
num_good_reads = ngs_reads['evaluation'].replace({'ugly': 0, 'good': 1}).sum()
print('Good quality:', num_good_reads, 'out of', num_reads)
print('Bad quality:', num_reads - num_good_reads, 'out of', num_reads)

Good quality: 110 out of 184
Bad quality: 74 out of 184


#### distribution of applied technologies

In [10]:
print('instances of technologies')
technologies = ngs_reads.technology.unique()
for technology in technologies:
    print(technology, ngs_reads[ngs_reads.technology == technology].shape[0])

instances of technologies
MS 80
HS 50
NX 54


#### distribution of organisms

In [11]:
print('instances of organisms')
organisms = ngs_reads.organism.unique()
for organism in organisms:
    print(organism, ngs_reads[ngs_reads.organism == organism].shape[0])

instances of organisms
Sau 78
Ecoli 18
Efcm 88


#### variable data size betweend reads

Tables within a module (column) have different lengths, which is problematic for usage as features in ML.  
Show different table lengths of all modules.  
Select unique combinations of lengths, organism and technology to check for correlation.

In [12]:
def unique_size_combinations(df, module_name):
    all_rows = []
    for i in range(df.shape[0]):
        count = str(df[module_name][i].shape[0]) + ' ' + df['organism'][i] + ' ' + df['technology'][i]
        all_rows.append(count)
    unique_combinations = Counter(all_rows).keys()
    combination_counts = Counter(all_rows).values()
    unique_counts = pd.DataFrame()
    unique_counts['combinations'] = unique_combinations
    unique_counts['counts'] = combination_counts
    return unique_counts

In [13]:
counts_per_base_sequence_quality = unique_size_combinations(ngs_reads, 'Per base sequence quality')
counts_per_tile_sequence_quality = unique_size_combinations(ngs_reads, 'Per base sequence quality')
counts_per_sequence_quality_scores = unique_size_combinations(ngs_reads, 'Per sequence quality scores')
counts_per_base_sequence_content = unique_size_combinations(ngs_reads, 'Per base sequence content')
counts_per_sequence_gc_content = unique_size_combinations(ngs_reads, 'Per sequence GC content')
counts_per_base_n_content = unique_size_combinations(ngs_reads, 'Per base N content')
counts_sequence_length_distribution = unique_size_combinations(ngs_reads, 'Per base sequence quality')
counts_sequence_duplication_levels = unique_size_combinations(ngs_reads, 'Sequence Duplication Levels')
counts_overrepresented_sequences = unique_size_combinations(ngs_reads, 'Overrepresented sequences')
counts_adapter_content = unique_size_combinations(ngs_reads, 'Adapter Content')

In [14]:
counts_per_base_sequence_quality

combinations  counts
0    68 Sau MS      38
1    58 Sau HS      20
2    38 Sau NX      20
3  68 Ecoli MS      10
4  58 Ecoli HS       8
5   68 Efcm MS      32
6   38 Efcm NX      34
7   58 Efcm HS      22

In [15]:
counts_per_tile_sequence_quality

combinations  counts
0    68 Sau MS      38
1    58 Sau HS      20
2    38 Sau NX      20
3  68 Ecoli MS      10
4  58 Ecoli HS       8
5   68 Efcm MS      32
6   38 Efcm NX      34
7   58 Efcm HS      22

In [16]:
counts_per_sequence_quality_scores

combinations  counts
0     36 Sau MS      17
1     25 Sau MS       6
2     26 Sau MS       6
3     23 Sau MS       1
4     28 Sau MS       3
5     22 Sau MS       1
6     28 Sau HS       2
7     31 Sau HS       1
8     33 Sau HS       1
9     38 Sau HS       7
10    27 Sau MS       3
11    33 Sau MS       1
12    22 Sau NX       6
13    21 Sau NX       4
14    23 Sau NX       2
15    34 Sau NX       4
16    20 Sau NX       4
17    24 Sau HS       4
18    37 Sau HS       3
19    25 Sau HS       2
20  36 Ecoli MS       8
21  25 Ecoli MS       1
22  23 Ecoli MS       1
23  34 Ecoli HS       3
24  23 Ecoli HS       1
25  25 Ecoli HS       2
26  38 Ecoli HS       2
27   21 Efcm MS       1
28   29 Efcm MS       2
29   23 Efcm MS       1
30   26 Efcm MS       4
31   34 Efcm MS       3
32   25 Efcm MS       3
33   30 Efcm MS       1
34   27 Efcm MS       1
35   17 Efcm NX       1
36   33 Efcm NX       4
37   18 Efcm NX       1
38   21 Efcm NX       3
39   22 Efcm NX       6
40   26 Efcm HS       1
41   38 Efcm HS      11
42   25 Efcm HS       3
43   32 Efcm HS       1
44   28 Efcm HS       2
45   31 Efcm HS       1
46   36 Efcm MS      16
47   24 Efcm NX       3
48   34 Efcm NX       6
49   29 Efcm NX       1
50   20 Efcm NX       6
51   31 Efcm NX       1
52   28 Efcm NX       1
53   26 Efcm NX       1
54   37 Efcm HS       1
55   24 Efcm HS       2

In [17]:
counts_per_base_sequence_content

combinations  counts
0    68 Sau MS      38
1    58 Sau HS      20
2    38 Sau NX      20
3  68 Ecoli MS      10
4  58 Ecoli HS       8
5   68 Efcm MS      32
6   38 Efcm NX      34
7   58 Efcm HS      22

In [18]:
counts_per_sequence_gc_content

combinations  counts
0    101 Sau MS      38
1    101 Sau HS      20
2    101 Sau NX      20
3  101 Ecoli MS      10
4  101 Ecoli HS       8
5   101 Efcm MS      32
6   101 Efcm NX      34
7   101 Efcm HS      22

In [19]:
counts_per_base_n_content

combinations  counts
0    68 Sau MS      38
1    58 Sau HS      20
2    38 Sau NX      20
3  68 Ecoli MS      10
4  58 Ecoli HS       8
5   68 Efcm MS      32
6   38 Efcm NX      34
7   58 Efcm HS      22

In [20]:
counts_sequence_length_distribution

combinations  counts
0    68 Sau MS      38
1    58 Sau HS      20
2    38 Sau NX      20
3  68 Ecoli MS      10
4  58 Ecoli HS       8
5   68 Efcm MS      32
6   38 Efcm NX      34
7   58 Efcm HS      22

In [21]:
counts_sequence_duplication_levels

combinations  counts
0    16 Sau MS      38
1    16 Sau HS      20
2    16 Sau NX      20
3  16 Ecoli MS      10
4  16 Ecoli HS       8
5   16 Efcm MS      32
6   16 Efcm NX      34
7   16 Efcm HS      22

In [22]:
counts_overrepresented_sequences

combinations  counts
0       0 Sau MS      30
1     334 Sau MS       2
2       0 Sau HS      20
3       1 Sau MS       6
4       0 Sau NX      20
5     1 Ecoli MS       2
6   949 Ecoli MS       1
7     0 Ecoli MS       6
8   947 Ecoli MS       1
9     0 Ecoli HS       8
10     0 Efcm MS      27
11     1 Efcm MS       5
12     0 Efcm NX      32
13     0 Efcm HS      16
14     2 Efcm NX       1
15     1 Efcm NX       1
16     1 Efcm HS       3
17     2 Efcm HS       3

In [23]:
counts_adapter_content

combinations  counts
0    66 Sau MS      38
1    56 Sau HS      20
2    36 Sau NX      20
3  66 Ecoli MS      10
4  56 Ecoli HS       8
5   66 Efcm MS      32
6   36 Efcm NX      34
7   56 Efcm HS      22

All modules except counts_per_base_n_content have variable table lengths.  
The following modules have the same distribution and in total 3 different lengths - 38, 58 or 68.  
* counts_per_base_sequence_quality
* counts_per_tile_sequence_quality
* counts_per_base_sequence_content
* counts_per_sequence_gc_content
* counts_per_base_n_content
* counts_sequence_length_distribution  

Solution to discover practical imputing technique seems challenging.  
Better solution might be to use calculated features like averages, maximums, minimums, counts. Would also help to solve another challenge with data preparation - transforming the dataframes to one dimensional features for the ML algorithms.